version: 2

models:
  - name: dm_monthly_trip_summary
    columns:
      - name: pickup_month
        data_types: string
      - name: monthly_total_revenue
        data_tupes: float
        tests:
          - not_null:
            severity: error
          - dbt_utils.accepted_range:
            min_value: 0
            inclusive: false
      - name: avg_monthly_passenger_count
        data_type: int64
        tests:
          - not_null:
            severity: error