services:
  pgdatabase:
    image: postgres:13
    container_name: pgdatabase
    environment:
      - xxx=xxx
    volumes:
      - xxx
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - name=value