services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    condition: service_healthy
    
  redis:
    image: redis:latest
    expose:
      - 6379
    condition: service_healthy